apiVersion: apps/v1
kind: Deployment
metadata:
  name: instance-metric-collector
  namespace: system-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: instance-metric-collector
      namespace: system-operator
  template:
    metadata:
      labels:
        name: instance-metric-collector
        namespace: system-operator
    spec:
      nodeSelector:
        layer: operator
      imagePullSecrets:
        - name: regcred
      containers:
        - name: instance-metric-collector
          image: ketidevit2/instance-metric-collector:v0.0.1
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DEBUGG_LEVEL
              value: "LEVEL1"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: COLLECT_INTERVAL
              value: "5"
            - name: INFLUX_IP
              value: "10.0.4.87"
            - name: INFLUX_PORT
              value: "30701"
            - name: INFLUX_USERNAME
              value: "keti"
            - name: INFLUX_PASSWORD
              value: "ketilinux"
          volumeMounts:
            - mountPath: /mnt/power
              name: metric-power
            - mountPath: /mnt/cpu
              name: metric-cpu-tick
      volumes:
        - name: metric-power
          hostPath:
            type: Directory
            path: /sys/devices/virtual/powercap/intel-rapl
        - name: metric-cpu-tick
          hostPath:
            type: Directory
            path: /proc
        - name: time
          hostPath:
            type: Directory
            path: /etc/localtime
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
