apiVersion: v1
kind: Service
metadata:
  name: query-engine-instance-svc
  namespace: keti-opencsd # 네임스페이스 가변
spec:
  type: NodePort
  ports:
  - port: 40100
    targetPort: 40100 
    protocol: TCP
    nodePort: 30100 # 노드포트(고유값) 가변
  selector:
    app: query-engine-instance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: query-engine-instance
  name: query-engine-instance
  namespace: keti-opencsd # 네임스페이스 가변
spec:
  selector:
    matchLabels:
      app: query-engine-instance
  template:
    metadata:
      labels:
        app: query-engine-instance
        tier : opencsd
      name: query-engine-instance
    spec:
      nodeSelector:
        layer: operation
      imagePullSecrets:
        - name: regcred
      containers:
        - name: query-engine
          image: ketidevit2/query-engine-instance:v3.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: host-sys
              mountPath: /host/sys
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
          resources: # 가변
            requests:
              memory: "128Mi"
              cpu: "250m"    
            limits:
              memory: "1Gi" 
              cpu: "1" 
          env:
          - name: LOG_LEVEL
            value: "INFO"
          - name: INSTANCE_TYPE
            value: "OPENCSD"
          - name: INSTANCE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: STORAGE_ENGINE_DNS
            value: "storage-engine-interface-svc.keti-opencsd.svc.cluster.local" # 네임스페이스 가변
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
        - name: host-sys
          hostPath:
            path: /sys
        - name: host-proc
          hostPath:
            path: /proc
