apiVersion: v1
kind: Service
metadata:
  name: storage-engine-interface-svc
  namespace: keti-opencsd # 가변
spec:
  ports:
  - port: 40200
    targetPort: 40200
    protocol: TCP
  selector:
    app: storage-engine-instance
---
apiVersion: v1
kind: Service
metadata:
  name: buffer-manager-svc
  namespace: keti-opencsd # 가변
spec:
  type: NodePort
  ports:
  - port: 40204
    targetPort: 40204
    protocol: TCP
    nodePort: 30204 # 노드포트(고유값) 가변
  selector:
    app: storage-engine-instance
---
apiVersion: v1
kind: Service
metadata:
  name: storage-engine-dbms-svc
  namespace: keti-opencsd # 가변
spec:
  ports:
  - name: main
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: storage-engine-instance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: storage-engine-instance
  name: storage-engine-instance
  namespace: keti-opencsd # 가변
spec:
  selector:
    matchLabels:
      app: storage-engine-instance
  template:
    metadata:
      labels:
        app: storage-engine-instance
        tier : opencsd
      name: storage-engine-instance
    spec:
      nodeSelector:
        layer: operation
      imagePullSecrets:
        - name: regcred
      containers:
        - name: interface-module
          image: ketidevit2/storage-engine-interface:v3.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
          resources: # 가변
            requests:
              memory: "128Mi"
              cpu: "250m"    
            limits:
              memory: "1Gi" 
              cpu: "1" 
          env:
          - name: LOG_LEVEL
            value: "INFO"
        - name: offloading-module
          image: ketidevit2/offloading-module:v3.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
          resources: # 가변
            requests:
              memory: "128Mi"
              cpu: "250m"    
            limits:
              memory: "5Gi" 
              cpu: "1" 
          env:
          - name: LOG_LEVEL
            value: "INFO"
          - name: STORAGE_NODE_IP
            value: "10.0.4.83" # 가변
        - name: merging-module
          image: ketidevit2/merging-module:v3.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
          resources: # 가변
            requests:
              memory: "1Gi"
              cpu: "1"    
            limits:
              memory: "100Gi" 
              cpu: "3" 
          env:
          - name: LOG_LEVEL
            value: "TRACE"
        - name: myrocks
          image: percona:5.7.43
          imagePullPolicy: Always
          securityContext:
            runAsUser: 999
          ports:
            - containerPort: 3306
          resources: # 가변
            requests:
              memory: "1G"
              cpu: "200m"
            limits:
              memory: "10G"
              cpu: "500m"
          env: # 가변
            - name: MYSQL_ROOT_PASSWORD
              value: keti
            - name: MYSQL_DATABASE
              value: testdb
            - name: INIT_ROCKSDB
              value: "yes"
          volumeMounts:
            - name: opencsd-csd-glusterfs
              mountPath: /var/lib/mysql
            - name: myrocks-cm
              mountPath: /etc/mysql
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
        - name: config
          hostPath:
            path: /root/.kube
        - name: opencsd-csd-glusterfs # 볼륨명: opencsd-{volume name}
          nfs: # 가변
            server: 10.0.4.83 # 마운팅 하려는 서버의 /etc/exports 에서 nfs 설정
            path: /mnt/gluster/client/keti-opencsd  # 해당 서버 권한 확인
        - name: myrocks-cm
          configMap:
            name:  mysql-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: keti-opencsd # 가변
  labels:
    app: storage-engine-instance
data:
   my.cnf: | # 전달받은 인자로 내용 구성
     [mysqld]
     user=mysql
     plugin-load-add = ha_rocksdb.so
     default-storage-engine=rocksdb
     
     

