apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-instance
  namespace: MYSQL_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-instance
  template:
    metadata:
      labels:
        name: mysql-instance
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        key: worker
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: metric
            - name: MYSQL_PASSWORD
              value: ketilinux
            - name: MYSQL_ROOT_PASSWORD
              value: ketilinux
            - name: MYSQL_USER
              value: keti
          image: mysql:latest
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
