apiVersion: v1
kind: Service
metadata:
  name: mysql-dbms-svc
  namespace: keti-mysql # 가변
spec:
  ports:
    - name: main
      port: 3307
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mysql-config
#   namespace: keti-mysql # 가변
#   labels:
#     app: mysql
# data:
#    my.cnf: | # 전달받은 인자로 내용 구성
#      [mysqld]
#      user=mysql
#      plugin-load-add = ha_rocksdb.so
#     #  default-storage-engine=rocksdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: keti-mysql # 가변
spec:
  replicas: 1
  serviceName: mysql-dbms-svc
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        tier: opencsd
    spec:
      nodeSelector:
        layer: operation
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: tpch_origin
            - name: MYSQL_PASSWORD
              value: ketilinux
            - name: MYSQL_ROOT_PASSWORD
              value: ketilinux
            - name: MYSQL_USER
              value: keti
          image: percona:5.7.43
          name: mysql
          ports:
            - containerPort: 3307
          volumeMounts:
            - name: opencsd-ssd-lvm
              mountPath: /var/lib/mysql
            # - name: mysql-config
            #   mountPath: /etc/mysql
            - name: mysql-data
              mountPath: /mnt/sql
      volumes:
        - name: opencsd-ssd-lvm
          nfs:
            server: 10.0.4.82
            path: /mnt/lvm/keti-mysql2
        # - name: mysql-config
        #   configMap:
        #     name: mysql-config
        - name: mysql-data
          hostPath:
            path: /root/workspace/keti/Generator/1.tpch_sst/sql  
