apiVersion: v1
kind: Service
metadata:
  name: query-engine-instance
  namespace: OPENCSD_NAMESPACE
  labels:
    name: query-engine-instance
spec:
  type: NodePort
  ports:
  - name: http
    port: 40100
    targetPort: 40100
    nodePort: 30100
    protocol: TCP
  selector:
    app: query-engine-instance
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: query-engine-instance
  namespace: OPENCSD_NAMESPACE
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: query-engine-instance
  namespace: OPENCSD_NAMESPACE
subjects:
- kind: ServiceAccount
  name: query-engine-instance
  namespace: OPENCSD_NAMESPACE
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: query-engine-instance
  name: query-engine-instance
  namespace: OPENCSD_NAMESPACE
spec:
  selector:
    matchLabels:
      app: query-engine-instance
  template:
    metadata:
      labels:
        app: query-engine-instance
      name: query-engine-instance
    spec:
      nodeSelector:
        key: worker
      serviceAccountName: query-engine-instance
      imagePullSecrets:
        - name: regcred
      containers:
        - name: query-engine
          image: ketidevit2/query-engine-instance:v1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: config
              mountPath: /root/.kube/  
          resources:
            limits:
              memory: "200Mi"
            requests:
              memory: "200Mi"
          env:
          - name: LOG_LEVEL
            value: "INFO"
          - name: QUERY_ENGINE_POD_PORT
            value: "40100"
          - name: SE_INTERFACE_CONTAINER_POD_PORT
            value: "30200"
          - name : CLUSTER_MASTER_IP
            value: "10.0.4.87"
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
        - name: config
          hostPath:
            path: /root/.kube
