apiVersion: v1
kind: Service
metadata:
  name: storage-engine-instance
  namespace: OPENCSD_NAMESPACE
  labels:
    name: storage-engine-instance
spec:
  type: NodePort
  ports:
  - name: interface-container
    port: 40200
    targetPort: 40200
    nodePort: 30200
    protocol: TCP
  - name: interface-container-http
    port: 40205
    targetPort: 40205
    nodePort: 30205
    protocol: TCP
  - name: offloading-container
    port: 40201
    targetPort: 40201
    nodePort: 30201
    protocol: TCP
  - name: offloading-container-http
    port: 40206
    targetPort: 40206
    nodePort: 30206
    protocol: TCP
  - name: merging-container
    port: 40202
    targetPort: 40202
    nodePort: 30202
    protocol: TCP
  - name: merging-container-csd
    port: 40204
    targetPort: 40204
    nodePort: 30204
    protocol: TCP
  - name: merging-container-http
    port: 40207
    targetPort: 40207
    nodePort: 30207
    protocol: TCP
  - name: monitoring-container
    port: 40203
    targetPort: 40203
    nodePort: 30203
    protocol: TCP
  - name: monitoring-container-http
    port: 40208
    targetPort: 40208
    nodePort: 30208
    protocol: TCP
  selector:
    app: storage-engine-instance
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-engine-instance
  namespace: OPENCSD_NAMESPACE
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-engine-instance
  namespace: OPENCSD_NAMESPACE
subjects:
- kind: ServiceAccount
  name: storage-engine-instance
  namespace: OPENCSD_NAMESPACE
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: storage-engine-instance
  name: storage-engine-instance
  namespace: OPENCSD_NAMESPACE
spec:
  selector:
    matchLabels:
      app: storage-engine-instance
  template:
    metadata:
      labels:
        app: storage-engine-instance
      name: storage-engine-instance
    spec:
      nodeSelector:
        key: worker
      serviceAccountName: storage-engine-instance
      imagePullSecrets:
        - name: regcred
      containers:
        - name: interface-container
          image: ketidevit2/interface-container:v1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: config
              mountPath: /root/.kube/  
          resources:
            requests:
              memory: "200Mi"
          env:
          - name: LOG_LEVEL
            value: "Info"
        - name: offloading-container
          image: ketidevit2/offloading-container:v1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: config
              mountPath: /root/.kube/  
          resources:
            requests:
              memory: "200Mi"
          env:
          - name: LOG_LEVEL
            value: "INFO"
          - name: SE_MERGING_CONTAINER_POD_PORT
            value: "30204"
        - name: merging-container
          image: ketidevit2/merging-container:v1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: config
              mountPath: /root/.kube/  
          resources:
            requests:
              memory: "200Mi"
          env:
          - name: LOG_LEVEL
            value: "INFO"
          - name: SE_MERGING_CONTAINER_POD_PORT
            value: "30204"
        - name: monitoring-container
          image: ketidevit2/monitoring-container:v1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: config
              mountPath: /root/.kube/  
          resources:
            requests:
              memory: "200Mi"
          env:
          - name: LOG_LEVEL
            value: "Info"
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
        - name: config
          hostPath:
            path: /root/.kube
