apiVersion: v1
kind: Service
metadata:
  name: validator-svc
  namespace: keti-opencsd # 가변
  labels:
    name: validator
spec:
  ports:
  - name: main
    port: 40000
    targetPort: 40000
    protocol: TCP
  - name: qemu
    port: 40001
    targetPort: 40001
    protocol: TCP
  selector:
    app: validator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: validator
    tier: opencsd
  name: validator
  namespace: keti-opencsd # 가변
spec:
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      labels:
        app: validator
      name: validator
    spec:
      nodeSelector:
        layer: operation
      imagePullSecrets:
        - name: regcred
      containers:
        - name: validator
          image: ketidevit2/validator:v1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: config
              mountPath: /root/.kube/  
          resources: # 가변
            requests:
              memory: "128Mi"
              cpu: "250m"    
            limits:
              memory: "1Gi" 
              cpu: "1" 
          env:
          - name: LOG_LEVEL
            value: "INFO"
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
        - name: config
          hostPath:
            path: /root/.kube
